CREATE TABLE IF NOT EXISTS book (
    ID INTEGER(90) NOT NULL PRIMARY KEY,
    TITLE VARCHAR(90) NOT NULL,
    COMPLETED BOOLEAN
);
INSERT INTO book(ID,TITLE, COMPLETED) VALUES(1,"DANI THE BEST",false)
